spring.application.name=notificationsAdrian

spring.datasource.url=jdbc:postgresql://localhost:5432/chatdb
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# Configuración de Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ¡LA MAGIA! Esto le dice a Spring que cree la tabla "messages" automáticamente
spring.jpa.hibernate.ddl-auto=update

# Ver las consultas SQL en la consola (útil para ver qué hace Spring por debajo)
spring.jpa.show-sql=true